добавляет функции по 2 дз
htmlacademy-javascript/2146421-kekstagram-28 pull request #2
Opened 2023-02-20 14:25 UTC by Velkatya

2023-02-21 13:23 UTC, pavel-nyukalo requested changes

2023-02-21 13:23 UTC, pavel-nyukalo commented on js/functions.js
> +const isStringFits = (str, lgth) => str.lenght <= lgth;
Я бы для большего понимания раскрыл бы `lgth` в `length`

2023-02-21 13:23 UTC, pavel-nyukalo commented on js/functions.js
> +  }
Если правильно понял, ты добавила сложность с числами.
В таком случае нужно доработать чуть функцию, поскольку сейчас она немного не по заданию возвращает

![image](https://user-images.githubusercontent.com/52506235/220356393-f03c5965-b9d9-4075-9920-fa026b0a8204.png)

![image](https://user-images.githubusercontent.com/52506235/220356416-40a4c9cd-a4a8-4774-8d37-47f8333992da.png)

![image](https://user-images.githubusercontent.com/52506235/220356439-bc548ff8-780b-4dce-8d75-d3f2d712745f.png)

2023-02-22 07:03 UTC, Velkatya commented on js/functions.js
> +  }
я поправила. А можно их как-то оптимизировать еще?

2023-02-24 18:31 UTC, pavel-nyukalo approved these changes

2023-02-24 18:31 UTC, merged